# Generated by Django 5.0 on 2024-01-09 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('status', models.CharField(max_length=30)),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('case_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('priority', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CorpseBlockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.CharField(max_length=100)),
                ('previous_hash', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('hash', models.CharField(editable=False, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceBlockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.CharField(max_length=100)),
                ('previous_hash', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('hash', models.CharField(editable=False, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseTeamMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.case')),
            ],
        ),
        migrations.CreateModel(
            name='Corpse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpse_no', models.CharField(max_length=50)),
                ('date_of_discovery', models.CharField(max_length=100)),
                ('discovery_location', models.CharField(max_length=500)),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.case')),
            ],
        ),
        migrations.CreateModel(
            name='AutopsyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('corpse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.corpse')),
            ],
        ),
        migrations.CreateModel(
            name='CorpseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('estimate_age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('cause_death', models.CharField(max_length=1000)),
                ('condition', models.CharField(max_length=5000)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('corpse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.corpse')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_no', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('evidence_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('collection_datetime', models.CharField(max_length=100)),
                ('collection_location', models.CharField(max_length=500)),
                ('collection_method', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=30)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.case')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_no', models.CharField(max_length=50)),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('analysis_techniques', models.CharField(max_length=200)),
                ('analysis_status', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=5000)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField()),
                ('case_team_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.caseteammapping')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.staff')),
            ],
        ),
        migrations.AddField(
            model_name='corpse',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.staff'),
        ),
        migrations.AddField(
            model_name='caseteammapping',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.staff'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('case_team_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcmsapp.caseteammapping')),
            ],
        ),
    ]
