# Generated by Django 5.0 on 2024-01-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
